Dshop/src/web/sgsz/config/routes.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
require './app/store'
Depot::Application.routes.draw do
  resources :memberprices

  resources :shippers

  resources :contactpayments

  post "orderdetails/del"
  post "orderdetails/add"
  post "orderdetails/sub"

  get "ordermains/open"
  get "ordermains/close"
  get "contactpayments/cust"

  match 'catalog' => StoreApp.new
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :customers
    resources :ordermains do
      resources :orderdetails
    end

    resources :orderdetails
    resources :carts
    resources :stocks do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

Dshop/src/web/sgsz/app/controllers/application_controller.rb
#---

#---
class ApplicationController < ActionController::Base
  before_filter :set_i18n_locale_from_params
  # ...
  before_filter :authorize
  protect_from_forgery

  private

    def current_cart 
      cart = Cart.find_by_id(session[:cart_id])
      if cart.nil?
        customer = Customer.find_by_id(session[:customer_id])
        cart = Cart.find_by_teller(customer.loginname)
        if cart.nil?
          cart = customer.build_cart
          session[:cart_id] = cart.id
          cart.teller = customer.loginname 
          cart.save
        end
      end
      cart
    end

    def current_ordermain 
      @cart = current_cart
      ordermain = Ordermain.find_by_id(session[:ordermain_id])
      if ordermain.nil?
        customer = Customer.find_by_id(session[:customer_id])
        ordermain = Ordermain.where("id = ?", @cart.orderdetails.first.ordermain_id).first
        if ordermain.nil?
          ordermain = Ordermain.new
          ordermain.customer_id = customer.id
          session[:ordermain_id] = ordermain.id
          ordermain.custid = customer.cid 
          ordermain.custstate = customer.state 
          ordermain.custname = customer.cname 
          ordermain.shopname = customer.shopname 
          ordermain.save
          @cart.orderdetails.each do |orderdetail|
            orderdetail.ordermain_id = ordermain.id
            orderdetail.save
          end
        end
      end
      ordermain 
    end


    # ...

  protected

    def authorize
      if request.format == Mime::HTML 
        unless Customer.find_by_id(session[:customer_id])
          redirect_to login_url, notice: "Please log in"
        end
      else
        authenticate_or_request_with_http_basic do |username, password|
          #customer = Customer.find_by_loginname(username)
          #customer && customer.authenticate(password)
          Customer.authenticate(username,password)
        end
      end
    end

    def set_i18n_locale_from_params
      if params[:locale]
        if I18n.available_locales.include?(params[:locale].to_sym)
          I18n.locale = params[:locale]
        else
          flash.now[:notice] = 
            "#{params[:locale]} translation not available"
          logger.error flash.now[:notice]
        end
      end
    end

    def default_url_options
      { locale: I18n.locale }
    end
end

Dshop/src/web/sgsz/app/helpers/application_helper.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

Dshop/src/web/sgsz/app/views/application/_menu.html.erb
<% if session[:user_id] %>
<div class="menu">
    <ul>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.stock' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.stocknews'), stocknews_path %></li>
                <li>
                    <%= link_to t('views.application.menu.stockrepairs'), stockrepairs_path %></li>
            </ul>
        </li>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.orders' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.orderstates'), orderstates_path %></li>
            </ul>
        </li>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.tips' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.stocktips'), stocktips_path %></li>
                <li>
                    <%= link_to t('views.application.menu.orderinshorts'), orderinshorts_path %></li>
            </ul>
        </li>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.analysisprofit' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.productionpreferences'), productionpreferences_path %></li>
                <li>
                    <%= link_to t('views.application.menu.delivertypes'), delivertypes_path %></li>
                <li>
                    <%= link_to t('views.application.menu.profitproductions'), profitproductions_path %></li>
                <li>
                    <%= link_to t('views.application.menu.profitareas'), profitareas_path %></li>
                <li>
                    <%= link_to t('views.application.menu.profitcustomers'), profitcustomers_path %></li>
                <li>
                    <%= link_to t('views.application.menu.profitshippers'), profitshippers_path %></li>
            </ul>
        </li>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.analysiscost' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.sellcostproductions'), sellcostproductions_path %></li>
                <li>
                    <%= link_to t('views.application.menu.sellcostcustomers'), sellcostcustomers_path %></li>
                <li>
                    <%= link_to t('views.application.menu.sellcostgifts'), sellcostgifts_path %></li>
            </ul>
        </li>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.transaction' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.statementdays'), statementdays_path %></li>
            </ul>
        </li>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.manage' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.stores'), stores_path %></li>
                <li>
                    <%= link_to t('views.application.menu.users'), users_path %></li>
                <li>
                    <%= link_to t('views.application.menu.customers'), customers_path %></li>
                <li>
                    <%= link_to t('views.application.menu.feeders'), feeders_path %></li>
                <li>
                    <%= link_to t('views.application.menu.shippers'), shippers_path %></li>
                <li>
                    <%= link_to t('views.application.menu.memberprices'), memberprices_path %></li>
                <li>
                    <%= link_to t('views.application.menu.stocks'), stocks_path %></li>
                <li>
                    <%= link_to t('views.application.menu.selllogmains'), selllogmains_path %></li>
                <li>
                    <%= link_to t('views.application.menu.selllogdetails'), selllogdetails_path %></li>
                <li>
                    <%= link_to t('views.application.menu.aftersellmains'), aftersellmains_path %></li>
                <li>
                    <%= link_to t('views.application.menu.afterselldetails'), afterselldetails_path %></li>
                <li>
                    <%= link_to t('views.application.menu.ordermains'), ordermains_path %></li>
                <li>
                    <%= link_to t('views.application.menu.orderdetails'), orderdetails_path %></li>
                <li>
                    <%= link_to t('views.application.menu.contactpayments'), contactpayments_path %></li>
                <li>
                    <%= link_to t('views.application.menu.purchases'), purchases_path %></li>
                <li>
                    <%= link_to t('views.application.menu.buylogs'), buylogs_path %></li>
                <li>
                    <%= link_to t('views.application.menu.units'), units_path %></li>
                <li>
                    <%= link_to t('views.application.menu.mauths'), mauths_path %></li>
            </ul>
        </li>
        <li>
            <a class="hide" href="">
                <%= t 'views.application.menu.system' %></a>
            <ul>
                <li>
                    <%= link_to t('views.application.menu.logout'), logout_path, :method =>:delete %></li>
            </ul>
        </li>
    </ul>
    <div class="clear"></div>
</div>
<br />
<% end %>