Dshop/src/web/sgsz/config/routes.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
require './app/store'
Depot::Application.routes.draw do
  resources :memberprices

  resources :shippers

  resources :contactpayments

  post "orderdetails/del"
  post "orderdetails/add"
  post "orderdetails/sub"

  get "ordermains/open"
  get "ordermains/close"
  get "contactpayments/cust"

  match 'catalog' => StoreApp.new
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :customers
    resources :ordermains do
      resources :orderdetails
    end

    resources :orderdetails
    resources :carts
    resources :stocks do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

Dshop/src/web/sgsz/app/models/memberprice.rb
class Memberprice < ActiveRecord::Base
  attr_accessible :barcode, :cdate, :color, :custid, :custname, :custtel, :enddate, :goodsname, :hprice, :pid, :remark, :size, :startdate, :unit, :volume
end

Dshop/src/web/sgsz/app/controllers/memberprices_controller.rb
class MemberpricesController < ApplicationController
  # GET /memberprices
  # GET /memberprices.json
  def index
    @memberprices = Memberprice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @memberprices }
    end
  end

  # GET /memberprices/1
  # GET /memberprices/1.json
  def show
    @memberprice = Memberprice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @memberprice }
    end
  end

  # GET /memberprices/new
  # GET /memberprices/new.json
  def new
    @memberprice = Memberprice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @memberprice }
    end
  end

  # GET /memberprices/1/edit
  def edit
    @memberprice = Memberprice.find(params[:id])
  end

  # POST /memberprices
  # POST /memberprices.json
  def create
    @memberprice = Memberprice.new(params[:memberprice])

    respond_to do |format|
      if @memberprice.save
        format.html { redirect_to @memberprice, notice: 'Memberprice was successfully created.' }
        format.json { render json: @memberprice, status: :created, location: @memberprice }
      else
        format.html { render action: "new" }
        format.json { render json: @memberprice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /memberprices/1
  # PUT /memberprices/1.json
  def update
    @memberprice = Memberprice.find(params[:id])

    respond_to do |format|
      if @memberprice.update_attributes(params[:memberprice])
        format.html { redirect_to @memberprice, notice: 'Memberprice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @memberprice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberprices/1
  # DELETE /memberprices/1.json
  def destroy
    @memberprice = Memberprice.find(params[:id])
    @memberprice.destroy

    respond_to do |format|
      format.html { redirect_to memberprices_url }
      format.json { head :no_content }
    end
  end
end

Dshop/src/web/sgsz/app/helpers/memberprices_helper.rb
module MemberpricesHelper
end

Dshop/src/web/sgsz/app/views/memberprices/_form.html.erb
<%= form_for(@memberprice) do |f| %>
  <% if @memberprice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@memberprice.errors.count, "error") %> prohibited this memberprice from being saved:</h2>

      <ul>
      <% @memberprice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pid %><br />
    <%= f.text_field :pid %>
  </div>
  <div class="field">
    <%= f.label :barcode %><br />
    <%= f.text_field :barcode %>
  </div>
  <div class="field">
    <%= f.label :goodsname %><br />
    <%= f.text_field :goodsname %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :unit %><br />
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :custid %><br />
    <%= f.text_field :custid %>
  </div>
  <div class="field">
    <%= f.label :custname %><br />
    <%= f.text_field :custname %>
  </div>
  <div class="field">
    <%= f.label :custtel %><br />
    <%= f.text_field :custtel %>
  </div>
  <div class="field">
    <%= f.label :startdate %><br />
    <%= f.date_select :startdate %>
  </div>
  <div class="field">
    <%= f.label :enddate %><br />
    <%= f.date_select :enddate %>
  </div>
  <div class="field">
    <%= f.label :hprice %><br />
    <%= f.text_field :hprice %>
  </div>
  <div class="field">
    <%= f.label :cdate %><br />
    <%= f.date_select :cdate %>
  </div>
  <div class="field">
    <%= f.label :remark %><br />
    <%= f.text_area :remark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Dshop/src/web/sgsz/app/views/memberprices/edit.html.erb
<h1>Editing memberprice</h1>

<%= render 'form' %>

<%= link_to 'Show', @memberprice %> |
<%= link_to 'Back', memberprices_path %>

Dshop/src/web/sgsz/app/views/memberprices/index.html.erb
<h1>Listing memberprices</h1>

<table>
  <tr>
    <th>Pid</th>
    <th>Barcode</th>
    <th>Goodsname</th>
    <th>Size</th>
    <th>Color</th>
    <th>Volume</th>
    <th>Unit</th>
    <th>Custid</th>
    <th>Custname</th>
    <th>Custtel</th>
    <th>Startdate</th>
    <th>Enddate</th>
    <th>Hprice</th>
    <th>Cdate</th>
    <th>Remark</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @memberprices.each do |memberprice| %>
  <tr>
    <td><%= memberprice.pid %></td>
    <td><%= memberprice.barcode %></td>
    <td><%= memberprice.goodsname %></td>
    <td><%= memberprice.size %></td>
    <td><%= memberprice.color %></td>
    <td><%= memberprice.volume %></td>
    <td><%= memberprice.unit %></td>
    <td><%= memberprice.custid %></td>
    <td><%= memberprice.custname %></td>
    <td><%= memberprice.custtel %></td>
    <td><%= memberprice.startdate %></td>
    <td><%= memberprice.enddate %></td>
    <td><%= memberprice.hprice %></td>
    <td><%= memberprice.cdate %></td>
    <td><%= memberprice.remark %></td>
    <td><%= link_to 'Show', memberprice %></td>
    <td><%= link_to 'Edit', edit_memberprice_path(memberprice) %></td>
    <td><%= link_to 'Destroy', memberprice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Memberprice', new_memberprice_path %>

Dshop/src/web/sgsz/app/views/memberprices/new.html.erb
<h1>New memberprice</h1>

<%= render 'form' %>

<%= link_to 'Back', memberprices_path %>

Dshop/src/web/sgsz/app/views/memberprices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Pid:</b>
  <%= @memberprice.pid %>
</p>

<p>
  <b>Barcode:</b>
  <%= @memberprice.barcode %>
</p>

<p>
  <b>Goodsname:</b>
  <%= @memberprice.goodsname %>
</p>

<p>
  <b>Size:</b>
  <%= @memberprice.size %>
</p>

<p>
  <b>Color:</b>
  <%= @memberprice.color %>
</p>

<p>
  <b>Volume:</b>
  <%= @memberprice.volume %>
</p>

<p>
  <b>Unit:</b>
  <%= @memberprice.unit %>
</p>

<p>
  <b>Custid:</b>
  <%= @memberprice.custid %>
</p>

<p>
  <b>Custname:</b>
  <%= @memberprice.custname %>
</p>

<p>
  <b>Custtel:</b>
  <%= @memberprice.custtel %>
</p>

<p>
  <b>Startdate:</b>
  <%= @memberprice.startdate %>
</p>

<p>
  <b>Enddate:</b>
  <%= @memberprice.enddate %>
</p>

<p>
  <b>Hprice:</b>
  <%= @memberprice.hprice %>
</p>

<p>
  <b>Cdate:</b>
  <%= @memberprice.cdate %>
</p>

<p>
  <b>Remark:</b>
  <%= @memberprice.remark %>
</p>


<%= link_to 'Edit', edit_memberprice_path(@memberprice) %> |
<%= link_to 'Back', memberprices_path %>