Dshop/src/web/sgsz/config/routes.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
require './app/store'
Depot::Application.routes.draw do
  resources :memberprices

  resources :shippers

  resources :contactpayments

  post "orderdetails/del"
  post "orderdetails/add"
  post "orderdetails/sub"

  get "ordermains/open"
  get "ordermains/close"
  get "contactpayments/cust"

  match 'catalog' => StoreApp.new
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :customers
    resources :ordermains do
      resources :orderdetails
    end

    resources :orderdetails
    resources :carts
    resources :stocks do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

Dshop/src/web/sgsz/app/views/admin/_menu.html.erb
<div id="menu">
  <% if session[:customer_id] %>
  <ul>
    <li><%= link_to t('.ordermainsopen'), new_ordermain_path %></li>
    <li><%= link_to t('.ordermainsclose'), ordermains_close_path %></li>
    <li><%= link_to t('.contactpayments'), contactpayments_path %></li>
  </ul>
<% end %>
</div>

Dshop/src/web/sgsz/app/views/admin/index.html.erb
<h1><%= t('.welcome') %></h1>

<%= t('.now') %> <%= Time.now %><br/> 