Dshop/src/web/sgsz/config/routes.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
require './app/store'
Depot::Application.routes.draw do
  resources :memberprices

  resources :shippers

  resources :contactpayments

  post "orderdetails/del"
  post "orderdetails/add"
  post "orderdetails/sub"

  get "ordermains/open"
  get "ordermains/close"
  get "contactpayments/cust"

  match 'catalog' => StoreApp.new
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  scope '(:locale)' do
    resources :customers
    resources :ordermains do
      resources :orderdetails
    end

    resources :orderdetails
    resources :carts
    resources :stocks do
      get :who_bought, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

Dshop/src/web/sgsz/app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.title') %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>" id="all">
<!-- START:i18n -->
  <div id="banner">
    <%= @page_title || t('.title') %>
    <br/>
      <% if session[:customer_id] %>
    <ul>
       <li><%= t('.cname') %><%= link_to session[:cname], Customer.find_by_cid(session[:cid]) %></li>
       <li><%= t('.cardno') %><%= link_to session[:cid], Customer.find_by_cid(session[:cid]) %>/</li>
    </ul>
    <br/>
    <ul>
       <li><%= link_to t('.logout'), logout_path , :method => :delete %></li>
    </ul>
      <% else %>
    <br/>
    <br/>
    <ul>
       <li><%= link_to t('.login'), login_path , :method => :get %></li>
    </ul>
      <% end %>
  </div>
<!-- END:i18n -->
  <div id="columns">
    <div id="side">

      <%= render "admin/menu" %>
      
      <!-- START:hidden_div -->
      <% if @cart %>
        <%= hidden_div_if(@cart.orderdetails.empty?, id: 'cart') do %>
          <%= render @cart %>
        <% end %>
      <% end %>
    <!-- END:hidden_div -->

      <%= render "store/category" %>

    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>